version: "3"  # optional since v1.27.0

services:
  app:
    build: 
      context: .
      args:
        PROXY: ${PROXY} 
    
    volumes:
    - ..:/usr/src/app:cached
    
    command: /bin/sh -c "while sleep 1000; do :; done" 